# Generated by Django 3.0.7 on 2020-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
    ]
