# Generated by Django 3.0.7 on 2020-07-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20200704_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
