# Generated by Django 3.0.7 on 2020-07-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20200704_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='apply',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.employee'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leave'),
        ),
    ]
