# Generated by Django 3.0.7 on 2020-07-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20200705_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.head'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.department'),
        ),
    ]
