# Generated by Django 3.0.7 on 2020-07-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20200705_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave',
            field=models.ManyToManyField(to='leave.leave'),
        ),
    ]
