# Generated by Django 3.0.7 on 2020-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_employee_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status1',
            field=models.CharField(choices=[('Pending', 'Pending')], default='Pending', max_length=200),
        ),
    ]
