# Generated by Django 3.0.7 on 2020-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_apply_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status1',
        ),
    ]
