# Generated by Django 3.0.7 on 2020-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_remove_apply_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status1',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
