# Generated by Django 3.0.7 on 2020-07-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_auto_20200712_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.JPEG', null=True, upload_to=''),
        ),
    ]
