# Generated by Django 3.0.7 on 2020-07-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_auto_20200712_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
