# Generated by Django 3.0.7 on 2020-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0022_auto_20200712_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='reason',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
