# Generated by Django 3.0.7 on 2020-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0024_auto_20200721_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave',
            field=models.ManyToManyField(default='Sick leaves', to='leave.leave'),
        ),
    ]
