# Generated by Django 3.0.7 on 2020-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0025_auto_20200804_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave',
            field=models.ManyToManyField(to='leave.leave'),
        ),
    ]
