# Generated by Django 3.0.7 on 2020-08-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0026_auto_20200804_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='head',
            new_name='department',
        ),
    ]
