# Generated by Django 3.0.7 on 2020-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0029_auto_20200813_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
