# Generated by Django 3.0.7 on 2020-08-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0030_auto_20200813_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='head',
        ),
    ]
