# Generated by Django 3.0.7 on 2020-08-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0031_remove_employee_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.head'),
        ),
    ]
