# Generated by Django 3.0.7 on 2020-08-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0032_employee_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='head',
        ),
    ]
