# Generated by Django 3.0.7 on 2020-08-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0038_remove_employee_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
