# Generated by Django 3.0.7 on 2020-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0039_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='employee',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
