# Generated by Django 3.0.7 on 2020-08-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0040_auto_20200813_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.employee'),
        ),
    ]
