# Generated by Django 3.0.7 on 2020-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0041_auto_20200813_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
