# Generated by Django 3.0.7 on 2020-08-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0042_apply_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='name',
        ),
    ]
