# Generated by Django 3.0.7 on 2020-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0043_remove_apply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
