# Generated by Django 3.0.7 on 2020-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0044_apply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status1',
        ),
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
